# monitoring/prometheus.yml
global:
  scrape_interval: 5s
  evaluation_interval: 5s

# Alert rules
rule_files:
  - 'alerts.yml'

scrape_configs:
  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
  
  - job_name: 'celery-metrics-aggregated'
    # Scrape interval might be 15s by default, but you might want faster for saturation
    scrape_interval: 5s 
    static_configs:
      # Target the single, dedicated endpoint that serves the aggregated metrics
      - targets: ['prometheus-exporter:8000']
