services:
  celery-worker:
    build:
      context: ./app
      dockerfile: Dockerfile
    # container_name: lab01-celery-worker
    depends_on:
      redis:
        condition: service_healthy
    labels:
      - __meta_docker_container_label_com_docker_compose_service
    environment:
      # - PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus-multiproc/${HOSTNAME}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./app:/app
      - prometheus-multiproc:/tmp/prometheus-multiproc:rw
    entrypoint: ["/app/entrypoint.sh"]
    command: celery -A celery_app worker --loglevel=info --pool=gevent --concurrency=400
    networks:
      - lab01-network


networks:
  lab01-network:
    driver: bridge

volumes:
  prometheus-multiproc:
