services:
  # Monitoring stack
  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: lab01-redis-exporter
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis://redis:6379
    ports:
      - "9121:9121"
    networks:
      - lab01-network

  prometheus:
    image: prom/prometheus:latest
    container_name: lab01-prometheus
    depends_on:
      prometheus-exporter:
        condition: service_healthy
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alerts.yml:/etc/prometheus/alerts.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d'
    networks:
      - lab01-network
  
  # The service that scrapes/collects the metrics (optional, but a common pattern)
  prometheus-exporter:
    build: 
      context: ./app
      dockerfile: Dockerfile 

    command: python /app/metrics_server.py # A simple server that calls prometheus_client.start_http_server
    ports:
      - "8000:8000"
    environment:
      # Must point to the SAME directory to read all the files
      - PROMETHEUS_MULTIPROC_DIR=/var/prom/metrics
    healthcheck:
      # Use curl to check the /healthz path on the exposed port
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      # Run the check every 5 seconds
      interval: 5s
      # Wait up to 3 seconds for the check to pass
      timeout: 3s
      # Consider the container healthy after 3 consecutive successful checks
      retries: 3
      # Start checking 30 seconds after the container starts
      start_period: 30s
    volumes:
      # Must mount the SAME volume to aggregate all files
      - prom_data:/var/prom/metrics

  grafana:
    image: grafana/grafana:latest
    container_name: lab01-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./monitoring/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./monitoring/grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./monitoring/dashboards:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana
    networks:
      - lab01-network


volumes:
  prometheus-data:
  grafana-data:
  prom-data:

networks:
  lab01-network:
    driver: bridge

