import os
from prometheus_client import start_http_server, CollectorRegistry
import time
import sys

# ----------------------------------------------------------------------
# Metrics Server Script
#
# This script is designed to run as the dedicated metrics exporter
# (the 'prometheus_exporter' service in your docker-compose.yml).
#
# It automatically reads all metric files generated by the worker processes
# (which are pointed to by the PROMETHEUS_MULTIPROC_DIR environment variable)
# and exposes them on an HTTP endpoint.
# ----------------------------------------------------------------------

# --- Configuration ---
PORT = 8000
# The registry used for aggregation when PROMETHEUS_MULTIPROC_DIR is set.
# We explicitly create a registry that will read from the environment directory.
REGISTRY = CollectorRegistry()
# ---------------------


def run_metrics_server():
    """
    Initializes and starts the HTTP server to expose aggregated metrics.
    """

    # 1. Check for the mandatory environment variable
    multiproc_dir = os.environ.get("PROMETHEUS_MULTIPROC_DIR")
    if not multiproc_dir:
        print("FATAL ERROR: PROMETHEUS_MULTIPROC_DIR environment variable is not set.")
        print(
            "This variable must point to the shared volume where metric files are stored."
        )
        sys.exit(1)

    print(f"✅ Starting Prometheus Exporter on port {PORT}")
    print(f"✅ Aggregating metrics from directory: {multiproc_dir}")

    # 2. Start the HTTP server.
    # We use a custom request handler to ensure we generate the latest
    # snapshot from the file-based metrics on every scrape.
    try:
        start_http_server(
            port=PORT,
            addr="0.0.0.0",
            registry=REGISTRY,  # Pass the aggregation registry
        )
    except OSError as e:
        print(f"FATAL ERROR: Could not bind to port {PORT}. Error: {e}")
        sys.exit(1)

    # The server is now running in a background thread.
    # The main thread needs to stay alive indefinitely.
    while True:
        # We can perform any lightweight health checks or logging here if needed.
        # For a simple exporter, just sleep.
        time.sleep(1)


if __name__ == "__main__":
    run_metrics_server()
